"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./financeiro.module.css";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:5000";
type FinancialSummary={from:string;to:string;revenue:number;orders:number;averageTicket:number;payments:{pix:number;card:number;cash:number};cmv:number;cmvPercentage:number;grossProfit:number;grossMarginPercentage:number;paidExpenses:number;pendingPayables:number;paidReceivables:number;pendingReceivables:number;netProfit:number;netMarginPercentage:number;daily:{date:string;revenue:number;orders:number}[]};
type Entry={id:string;type:string;category:string;description:string;amount:number;dueDate:string;status:string;paymentMethod?:string;paidAt?:string};
const money=(v?:number|null)=>(typeof v==="number"?v:0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const pct=(v?:number|null)=>`${(typeof v==="number"?v:0).toFixed(1)}%`;
const isoDate=(d:Date)=>d.toISOString().slice(0,10);

export default function FinanceiroPage(){
 const[data,setData]=useState<FinancialSummary|null>(null);const[entries,setEntries]=useState<Entry[]>([]);const[error,setError]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
 const today=new Date();const[from,setFrom]=useState(isoDate(today));const[to,setTo]=useState(isoDate(today));
 const[type,setType]=useState("PAYABLE");const[category,setCategory]=useState("FORNECEDOR");const[description,setDescription]=useState("");const[amount,setAmount]=useState("");const[dueDate,setDueDate]=useState(isoDate(today));
 async function api(path:string,options:RequestInit={}){const token=localStorage.getItem("token");if(!token){location.href="/";throw new Error("Sessão expirada.")}const r=await fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}});const text=await r.text();if(!r.ok){try{throw new Error(JSON.parse(text).message??text)}catch{throw new Error(text||"Erro na operação.")}}return text?JSON.parse(text):null}
 async function load(){setLoading(true);setError("");try{const[s,e]=await Promise.all([api(`/api/financial/summary?from=${from}&to=${to}`),api("/api/financial/entries")]);setData(s);setEntries(e)}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar financeiro.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 function preset(days:number){const end=new Date();const start=new Date();start.setDate(end.getDate()-(days-1));setFrom(isoDate(start));setTo(isoDate(end));setTimeout(load,0)}
 async function createEntry(){if(!description||Number(amount)<=0)return;setMessage("");try{await api("/api/financial/entries",{method:"POST",body:JSON.stringify({type,category,description,amount:Number(amount),dueDate:new Date(`${dueDate}T12:00:00`).toISOString()})});setDescription("");setAmount("");setMessage(type==="PAYABLE"?"Conta a pagar cadastrada.":"Conta a receber cadastrada.");await load()}catch(e){setError(e instanceof Error?e.message:"Erro ao cadastrar.")}}
 async function payEntry(id:string){try{await api(`/api/financial/entries/${id}/pay`,{method:"PATCH",body:JSON.stringify({paymentMethod:"PIX"})});setMessage("Lançamento liquidado.");await load()}catch(e){setError(e instanceof Error?e.message:"Erro ao liquidar.")}}
 async function deleteEntry(id:string){if(!confirm("Excluir este lançamento?"))return;try{await api(`/api/financial/entries/${id}`,{method:"DELETE"});await load()}catch(e){setError(e instanceof Error?e.message:"Erro ao excluir.")}}
 const maxRevenue=useMemo(()=>Math.max(1,...(data?.daily??[]).map(x=>x.revenue)),[data]);
 if(loading&&!data)return <main className={styles.page}>Carregando financeiro...</main>;
 return <main className={styles.page}>
  <header><div><a href="/">← Voltar ao painel</a><h1>Financeiro</h1><p>DRE simplificada, contas e vendas por período.</p></div><button onClick={load}>Atualizar</button></header>
  <section className={styles.filters}><div><button onClick={()=>preset(1)}>Hoje</button><button onClick={()=>preset(7)}>7 dias</button><button onClick={()=>preset(30)}>30 dias</button></div><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={load}>Aplicar período</button></section>
  {error&&<div className={styles.error}>{error}</div>}{message&&<div className={styles.success}>{message}</div>}
  {data&&<><section className={styles.cards}><Metric label="Faturamento" value={money(data.revenue)}/><Metric label="Pedidos pagos" value={String(data.orders)}/><Metric label="Ticket médio" value={money(data.averageTicket)}/><Metric label="CMV" value={money(data.cmv)} sub={pct(data.cmvPercentage)}/><Metric label="Lucro bruto" value={money(data.grossProfit)} sub={pct(data.grossMarginPercentage)}/><Metric label="Despesas pagas" value={money(data.paidExpenses)}/><Metric label="Lucro líquido estimado" value={money(data.netProfit)} sub={pct(data.netMarginPercentage)}/><Metric label="Contas a pagar" value={money(data.pendingPayables)}/></section>
  <section className={styles.panel}><h2>DRE simplificada</h2><div className={styles.dre}><span>Receita de vendas <strong>{money(data.revenue)}</strong></span><span>(−) CMV <strong>{money(data.cmv)}</strong></span><span>= Lucro bruto <strong>{money(data.grossProfit)}</strong></span><span>(−) Despesas pagas <strong>{money(data.paidExpenses)}</strong></span><span className={styles.total}>= Lucro líquido estimado <strong>{money(data.netProfit)}</strong></span></div></section>
  <section className={styles.panel}><h2>Formas de pagamento</h2><div className={styles.payments}><Metric label="Pix" value={money(data.payments.pix)}/><Metric label="Cartão" value={money(data.payments.card)}/><Metric label="Dinheiro" value={money(data.payments.cash)}/></div></section>
  <section className={styles.panel}><h2>Faturamento por dia</h2>{data.daily.length?<div className={styles.chart}>{data.daily.map(d=><div className={styles.barRow} key={d.date}><span>{new Date(d.date).toLocaleDateString("pt-BR")}</span><div className={styles.track}><div className={styles.bar} style={{width:`${Math.max(4,d.revenue/maxRevenue*100)}%`}}/></div><strong>{money(d.revenue)}</strong></div>)}</div>:<p>Sem vendas no período.</p>}</section>
  <section className={styles.accounts}><div className={styles.panel}><h2>Novo lançamento</h2><div className={styles.formGrid}><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="PAYABLE">Conta a pagar</option><option value="RECEIVABLE">Conta a receber</option></select></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}><option>FORNECEDOR</option><option>ALUGUEL</option><option>ENERGIA</option><option>AGUA</option><option>INTERNET</option><option>FUNCIONARIOS</option><option>IMPOSTOS</option><option>MARKETING</option><option>MANUTENCAO</option><option>OUTROS</option></select></label><label>Descrição<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: Conta de energia"/></label><label>Valor<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Vencimento<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><button onClick={createEntry}>Cadastrar</button></div></div>
  <div className={styles.panel}><h2>Resumo de contas</h2><div className={styles.cardsSmall}><Metric label="A pagar" value={money(data.pendingPayables)}/><Metric label="A receber" value={money(data.pendingReceivables)}/><Metric label="Recebido" value={money(data.paidReceivables)}/></div></div></section>
  <section className={styles.panel}><h2>Contas cadastradas</h2>{entries.length?<div className={styles.list}>{entries.map(item=><div className={styles.entryRow} key={item.id}><div><strong>{item.description}</strong><small>{item.type==="PAYABLE"?"A pagar":"A receber"} · {item.category} · vence {new Date(item.dueDate).toLocaleDateString("pt-BR")}</small></div><strong>{money(item.amount)}</strong><span className={item.status==="PAID"?styles.paid:styles.pending}>{item.status==="PAID"?"Liquidado":"Pendente"}</span><div className={styles.rowActions}>{item.status!=="PAID"&&<button onClick={()=>payEntry(item.id)}>Liquidar</button>}<button className={styles.delete} onClick={()=>deleteEntry(item.id)}>Excluir</button></div></div>)}</div>:<p>Nenhum lançamento cadastrado.</p>}</section>
  <section className={styles.note}><strong>Como calculamos:</strong> lucro líquido estimado = faturamento − CMV − despesas pagas no período. Contas pendentes aparecem separadamente e só reduzem o lucro quando liquidadas.</section></>}
 </main>
}
function Metric({label,value,sub}:{label:string;value:string;sub?:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
