"use client";
import { useEffect, useMemo, useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:5000";
type Summary={revenue:number;orders:number;averageTicket:number;criticalStock:number;openOrders:number};
type Product={id:string;name:string;description?:string;price:number};
type Ingredient={id:string;name:string;unit:string;currentQuantity:number;minimumQuantity:number;costPerUnit:number};
type Table={id:string;number:number;seats:number;status:string};
function money(v:number){return v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
export default function Home(){const[token,setToken]=useState<string|null>(null);const[email,setEmail]=useState("admin@demo.local");const[password,setPassword]=useState("Admin@123");const[summary,setSummary]=useState<Summary|null>(null);const[products,setProducts]=useState<Product[]>([]);const[stock,setStock]=useState<Ingredient[]>([]);const[tables,setTables]=useState<Table[]>([]);const[q,setQ]=useState("");const[answer,setAnswer]=useState("");const[tab,setTab]=useState("dashboard");const[loginError,setLoginError]=useState("");const[productName,setProductName]=useState("");const[productPrice,setProductPrice]=useState("");const[ingredientName,setIngredientName]=useState("");
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});if(!r.ok)throw new Error(await r.text());return r.json()}
async function login(){try{const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})});localStorage.setItem("token",d.token);setToken(d.token);setLoginError("")}catch{setLoginError("E-mail ou senha inválidos.")}}
async function load(){if(!token)return;try{const[s,p,i,t]=await Promise.all([api("/api/dashboard/summary"),api("/api/products"),api("/api/stock"),api("/api/tables")]);setSummary(s);setProducts(p);setStock(i);setTables(t)}catch{localStorage.removeItem("token");setToken(null)}}
useEffect(()=>{const t=localStorage.getItem("token");if(t)setToken(t)},[]);useEffect(()=>{load()},[token]);
async function addProduct(){if(!productName||!productPrice)return;await api("/api/products",{method:"POST",body:JSON.stringify({name:productName,price:Number(productPrice),active:true})});setProductName("");setProductPrice("");load()}
async function addIngredient(){if(!ingredientName)return;await api("/api/stock",{method:"POST",body:JSON.stringify({name:ingredientName,unit:"un",currentQuantity:0,minimumQuantity:0,costPerUnit:0})});setIngredientName("");load()}
async function ask(){if(!q)return;const d=await api("/api/ai/ask",{method:"POST",body:JSON.stringify({question:q})});setAnswer(d.answer)}
if(!token)return <main className="login"><div className="loginCard"><h1>🍽️ Restaurante Inteligente</h1><p>Gestão completa para sua operação</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha"/><button onClick={login}>Entrar</button>{loginError&&<p className="error">{loginError}</p>}<small>Demo: admin@demo.local / Admin@123</small></div></main>;
return <div className="app"><aside><h2>🍽️ RestoIA</h2>{["dashboard","produtos","estoque","mesas","pedidos","ia"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}<button onClick={()=>{localStorage.removeItem("token");setToken(null)}}>Sair</button></aside><main className="content"><header><div><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1><p>Painel de gestão do restaurante</p></div><button onClick={load}>↻ Atualizar</button></header>{tab==="dashboard"&&<><section className="cards"><Card title="Faturamento hoje" value={summary?money(summary.revenue):"—"}/><Card title="Pedidos hoje" value={summary?.orders??"—"}/><Card title="Ticket médio" value={summary?money(summary.averageTicket):"—"}/><Card title="Estoque crítico" value={summary?.criticalStock??"—"}/><Card title="Pedidos abertos" value={summary?.openOrders??"—"}/></section><section className="panel"><h2>Assistente Inteligente</h2><div className="ask"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex.: Qual foi meu faturamento hoje?"/><button onClick={ask}>Perguntar</button></div>{answer&&<div className="answer">{answer}</div>}</section></>}{tab==="produtos"&&<Panel title="Produtos"><div className="form"><input value={productName} onChange={e=>setProductName(e.target.value)} placeholder="Nome do produto"/><input value={productPrice} onChange={e=>setProductPrice(e.target.value)} placeholder="Preço" type="number"/><button onClick={addProduct}>Adicionar</button></div><List items={products.map(p=>`${p.name} — ${money(p.price)}`)}/></Panel>}{tab==="estoque"&&<Panel title="Estoque"><div className="form"><input value={ingredientName} onChange={e=>setIngredientName(e.target.value)} placeholder="Ingrediente"/><button onClick={addIngredient}>Adicionar</button></div><List items={stock.map(i=>`${i.name} — ${i.currentQuantity} ${i.unit} ${i.currentQuantity<=i.minimumQuantity?"⚠️ crítico":""}`)}/></Panel>}{tab==="mesas"&&<Panel title="Mapa de mesas"><div className="tables">{tables.map(t=><div className={`table ${t.status.toLowerCase()}`} key={t.id}><strong>Mesa {t.number}</strong><span>{t.status}</span></div>)}</div></Panel>}{tab==="pedidos"&&<Panel title="Pedidos"><p>O backend já possui criação e fechamento de pedidos. O próximo passo é montar a tela operacional de garçom/caixa e KDS.</p></Panel>}{tab==="ia"&&<Panel title="Assistente IA"><div className="ask"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pergunte sobre vendas ou estoque"/><button onClick={ask}>Analisar</button></div>{answer&&<div className="answer">{answer}</div>}<p>Azure OpenAI fica preparado para análises avançadas depois que as regras de consulta estiverem configuradas.</p></Panel>}</main></div>}
function Card({title,value}:{title:string;value:string|number}){return <div className="card"><span>{title}</span><strong>{value}</strong></div>};function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><h2>{title}</h2>{children}</section>};function List({items}:{items:string[]}){return <div className="list">{items.length?items.map((x,i)=><div key={i}>{x}</div>):<p>Nenhum registro.</p>}</div>}
