"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./clientes.module.css";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5000";

type Customer = {id:string;name:string;phone?:string;email?:string;birthDate?:string;points:number;cashbackBalance:number;active:boolean;createdAt:string};
type CustomerDetail = {customer:Customer;stats:{orders:number;totalSpent:number;averageTicket:number;lastPurchase?:string};orders:{id:string;total:number;status:string;paymentMethod?:string;createdAt:string;closedAt?:string}[];loyalty:{id:string;type:string;points:number;cashback:number;description:string;createdAt:string}[]};
type Summary = {customers:number;customersWithPurchase:number;points:number;cashback:number};
type Coupon = {id:string;code:string;description:string;discountType:string;value:number;minimumOrderValue:number;maxUses?:number;uses:number;expiresAt?:string;active:boolean};

const money=(v?:number|null)=>(typeof v==="number"?v:0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function ClientesPage(){
 const[customers,setCustomers]=useState<Customer[]>([]);const[selectedId,setSelectedId]=useState("");const[detail,setDetail]=useState<CustomerDetail|null>(null);const[summary,setSummary]=useState<Summary|null>(null);const[coupons,setCoupons]=useState<Coupon[]>([]);const[search,setSearch]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
 const[name,setName]=useState("");const[phone,setPhone]=useState("");const[email,setEmail]=useState("");const[birthDate,setBirthDate]=useState("");
 const[points,setPoints]=useState("");const[cashback,setCashback]=useState("");const[loyaltyDescription,setLoyaltyDescription]=useState("");
 const[couponCode,setCouponCode]=useState("");const[couponDescription,setCouponDescription]=useState("");const[discountType,setDiscountType]=useState("PERCENT");const[couponValue,setCouponValue]=useState("");const[minOrder,setMinOrder]=useState("0");const[maxUses,setMaxUses]=useState("");const[expiresAt,setExpiresAt]=useState("");

 async function api(path:string,options:RequestInit={}){const token=localStorage.getItem("token");if(!token){location.href="/";throw new Error("Sessão expirada.");}const r=await fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`}});const text=await r.text();if(!r.ok){try{const d=JSON.parse(text);throw new Error(d.message??text)}catch(e){if(e instanceof Error&&e.message!==text)throw e;throw new Error(text||"Erro na operação.")}}return text?JSON.parse(text):null}

 async function load(){setLoading(true);setMessage("");try{const q=search.trim()?`?search=${encodeURIComponent(search.trim())}`:"";const[c,s,cp]=await Promise.all([api(`/api/customers${q}`),api("/api/customers/summary"),api("/api/customers/coupons")]);setCustomers(c);setSummary(s);setCoupons(cp)}catch(e){setMessage(e instanceof Error?e.message:"Erro ao carregar CRM.")}finally{setLoading(false)}}
 async function loadDetail(id:string){setSelectedId(id);try{setDetail(await api(`/api/customers/${id}`))}catch(e){setMessage(e instanceof Error?e.message:"Erro ao carregar cliente.")}}
 useEffect(()=>{load()},[]);

 async function createCustomer(){if(!name.trim())return;setMessage("");try{const created=await api("/api/customers",{method:"POST",body:JSON.stringify({name,phone:phone||null,email:email||null,birthDate:birthDate||null})});setName("");setPhone("");setEmail("");setBirthDate("");setMessage("Cliente cadastrado com sucesso.");await load();await loadDetail(created.id)}catch(e){setMessage(e instanceof Error?e.message:"Erro ao cadastrar cliente.")}}
 async function adjustLoyalty(){if(!selectedId)return;try{await api(`/api/customers/${selectedId}/loyalty`,{method:"POST",body:JSON.stringify({points:Number(points||0),cashback:Number(cashback||0),description:loyaltyDescription||null})});setPoints("");setCashback("");setLoyaltyDescription("");setMessage("Saldo de fidelidade atualizado.");await Promise.all([load(),loadDetail(selectedId)])}catch(e){setMessage(e instanceof Error?e.message:"Erro ao ajustar fidelidade.")}}
 async function createCoupon(){try{await api("/api/customers/coupons",{method:"POST",body:JSON.stringify({code:couponCode,description:couponDescription||null,discountType,value:Number(couponValue),minimumOrderValue:Number(minOrder||0),maxUses:maxUses?Number(maxUses):null,expiresAt:expiresAt||null})});setCouponCode("");setCouponDescription("");setCouponValue("");setMaxUses("");setExpiresAt("");setMessage("Cupom criado com sucesso.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Erro ao criar cupom.")}}
 async function toggleCoupon(id:string){try{await api(`/api/customers/coupons/${id}/toggle`,{method:"PATCH"});await load()}catch(e){setMessage(e instanceof Error?e.message:"Erro ao alterar cupom.")}}

 const selectedCustomer=useMemo(()=>customers.find(x=>x.id===selectedId),[customers,selectedId]);

 if(loading)return <main className={styles.page}>Carregando CRM...</main>;
 return <main className={styles.page}>
  <header><div><a href="/">← Voltar ao painel</a><h1>CRM · Clientes</h1><p>Cadastro, histórico de compras, fidelidade, cashback e cupons.</p></div><button onClick={load}>Atualizar</button></header>
  {message&&<div className={styles.message}>{message}</div>}
  <section className={styles.cards}><Metric label="Clientes ativos" value={String(summary?.customers??0)}/><Metric label="Já compraram" value={String(summary?.customersWithPurchase??0)}/><Metric label="Pontos em circulação" value={String(summary?.points??0)}/><Metric label="Cashback em circulação" value={money(summary?.cashback)}/></section>

  <section className={styles.grid}>
   <div className={styles.panel}><h2>Novo cliente</h2><div className={styles.form}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Telefone"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mail"/><label>Data de nascimento<input type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)}/></label><button onClick={createCustomer}>Cadastrar cliente</button></div></div>
   <div className={styles.panel}><h2>Buscar clientes</h2><div className={styles.search}><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Nome, telefone ou e-mail"/><button onClick={load}>Buscar</button></div><div className={styles.list}>{customers.length?customers.map(c=><button className={`${styles.customerRow} ${selectedId===c.id?styles.selected:""}`} key={c.id} onClick={()=>loadDetail(c.id)}><div><strong>{c.name}</strong><small>{c.phone||c.email||"Sem contato"}</small></div><span>{c.points} pts · {money(c.cashbackBalance)}</span></button>):<p>Nenhum cliente encontrado.</p>}</div></div>
  </section>

  {detail&&<section className={styles.panel}><div className={styles.detailHead}><div><h2>{detail.customer.name}</h2><p>{detail.customer.phone||"Sem telefone"} · {detail.customer.email||"Sem e-mail"}</p></div><div className={styles.badges}><span>{detail.customer.points} pontos</span><span>{money(detail.customer.cashbackBalance)} cashback</span></div></div><div className={styles.cards}><Metric label="Compras" value={String(detail.stats.orders)}/><Metric label="Total gasto" value={money(detail.stats.totalSpent)}/><Metric label="Ticket médio" value={money(detail.stats.averageTicket)}/><Metric label="Última compra" value={detail.stats.lastPurchase?new Date(detail.stats.lastPurchase).toLocaleDateString("pt-BR"):"—"}/></div><div className={styles.twoCols}><div><h3>Ajustar fidelidade</h3><div className={styles.form}><input type="number" value={points} onChange={e=>setPoints(e.target.value)} placeholder="Pontos (+ ou -)"/><input type="number" step="0.01" value={cashback} onChange={e=>setCashback(e.target.value)} placeholder="Cashback (+ ou -)"/><input value={loyaltyDescription} onChange={e=>setLoyaltyDescription(e.target.value)} placeholder="Motivo"/><button onClick={adjustLoyalty}>Aplicar ajuste</button></div></div><div><h3>Histórico de compras</h3><div className={styles.list}>{detail.orders.length?detail.orders.map(o=><div className={styles.historyRow} key={o.id}><div><strong>{money(o.total)}</strong><small>{new Date(o.createdAt).toLocaleString("pt-BR")}</small></div><span>{o.status} · {o.paymentMethod||"—"}</span></div>):<p>Nenhuma compra vinculada ainda.</p>}</div></div></div><h3>Movimentações de fidelidade</h3><div className={styles.list}>{detail.loyalty.length?detail.loyalty.map(l=><div className={styles.historyRow} key={l.id}><div><strong>{l.description}</strong><small>{new Date(l.createdAt).toLocaleString("pt-BR")}</small></div><span>{l.points>=0?"+":""}{l.points} pts · {l.cashback>=0?"+":""}{money(l.cashback)}</span></div>):<p>Nenhuma movimentação.</p>}</div></section>}

  <section className={styles.panel}><h2>Cupons promocionais</h2><div className={styles.couponForm}><input value={couponCode} onChange={e=>setCouponCode(e.target.value.toUpperCase())} placeholder="Código: VOLTA10"/><input value={couponDescription} onChange={e=>setCouponDescription(e.target.value)} placeholder="Descrição"/><select value={discountType} onChange={e=>setDiscountType(e.target.value)}><option value="PERCENT">Percentual</option><option value="FIXED">Valor fixo</option></select><input type="number" min="0.01" step="0.01" value={couponValue} onChange={e=>setCouponValue(e.target.value)} placeholder="Desconto"/><input type="number" min="0" step="0.01" value={minOrder} onChange={e=>setMinOrder(e.target.value)} placeholder="Pedido mínimo"/><input type="number" min="1" value={maxUses} onChange={e=>setMaxUses(e.target.value)} placeholder="Máx. usos"/><input type="date" value={expiresAt} onChange={e=>setExpiresAt(e.target.value)}/><button onClick={createCoupon}>Criar cupom</button></div><div className={styles.list}>{coupons.length?coupons.map(c=><div className={styles.couponRow} key={c.id}><div><strong>{c.code}</strong><small>{c.description} · mínimo {money(c.minimumOrderValue)}</small></div><span>{c.discountType==="PERCENT"?`${c.value}%`:money(c.value)} · {c.uses}/{c.maxUses??"∞"}</span><button className={c.active?styles.activeBtn:styles.inactiveBtn} onClick={()=>toggleCoupon(c.id)}>{c.active?"Ativo":"Inativo"}</button></div>):<p>Nenhum cupom cadastrado.</p>}</div></section>
  <section className={styles.note}><strong>Regra automática inicial:</strong> pedidos vinculados a clientes geram 1 ponto por R$ 1 gasto e 2% de cashback quando o pagamento é concluído. A próxima etapa é selecionar o cliente diretamente no pedido e aplicar cupons/cashback no fechamento.</section>
 </main>
}

function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
